services:
  mqtt-dashboard:
    build: .
    container_name: mqtt-dashboard
    ports:
      - "4001:3000"
    environment:
      # Change this to point to your MQTT Broker URL
      - BROKER=mqtt://192.168.68.106:1885
      # - MQTT_USERNAME=your_username
      # - MQTT_PASSWORD=your_password
    restart: unless-stopped
